rate: 25
pid_list: [{name: "turret_pid",
            feedback_topic: "/turret/feedback",
            setpoint_topic: "/turret/setpoint",
            control_topic: "/turret/cmd_vel",
            control_max: 15,
            control_min: -15,
            kp: 0.04,
            ki: 0.0,
            kd: 0,
            kf: 0},
            {name: "turn_pid",
            feedback_topic: "/navx/imu",
            setpoint_topic: "/turn/setpoint",
            control_topic: "/turn/cmd_vel",
            control_max: 2,
            control_min: -2,
            kp: 2.5,
            ki: 0.0,
            kd: 0,
            kf: 0}]
